version: '3.8'

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    container_name: node-app

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"   # Change port to 8081 to avoid Jenkins conflict
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    container_name: nginx
